spring.application.name=com.SocialMedia

spring.datasource.url=jdbc:mysql://localhost:3306/SocialMedia 
spring.datasource.username=root
spring.datasource.password=Sujit19

spring.jpa.hibernate.ddl-auto=update